### ISSUE TITLE
[FEATURE] Will gstreamer plugin such as `kvssrc` be supported in the future?

### ISSUE THREAD

**Issue by LittleWat** [aws/amazon-kinesis-video-streams-parser-library#129]
In kinesis video producer library, gstreamer plugin `kvssink` is supported.
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

Will gstreamer plugin such as `kvssrc` be supported in the future?

Or do we have to use HLS/DASH URL for GStreamer input? (https://gstreamer.freedesktop.org/documentation/hls/hlsdemux.html?gi-language=c#hlsdemux)

**Comment by hassanctech** [comment]
A `kvssrc` is one of many projects we have considered but there are no immediate plans for it.  If we did this work it would likely be built on top of a C consumer library (similar to how the `kvssink` is built on top of the C producer library, well C++ at the moment but that is only due to historical reasons that the C++ SDK predates the C SDK) at present we do not have a lower level consumer library.

Other than HLS/DASH we also have the GetMedia APIs that you can call directly if you're looking to consume the video with low latency but of course it won't be nearly as simple as a `kvssrc` plugin :).

**Comment by LittleWat** [comment]
@hassanctech Thank you for your reply!

I will use the GetMedia API !  It would be great if `kvssrc` in C producer library is supported in the future.
