### ISSUE TITLE
How to use this Parser Library in Android Project?

### ISSUE THREAD

**Issue by cjfei** [aws/amazon-kinesis-video-streams-parser-library#138]
Help needed. I have added some metadata from producer side using kvs producer cpp.  Now I want to retrieve the mkv metadata using Stream Parser Library and display it on my android App.  I import the Parser Libary into my android project by "implementation 'com.amazonaws:amazon-kinesis-video-streams-parser-library:1.0.15' ", but the android project cannot be built.  I dont know how to start in android project.  Can anyone tell how to retrieve metadata in android project? 

IDE: Android Studio (v4.1)
Language: Java.
OS:  Window 10.

**Comment by Tseema** [comment]
were able get this sorted? if yes could you pls explain the solution?

**Comment by sirknightj** [comment]
Hi @cjfei, it would be great if you could share the error messages you are seeing so we can help out further.

I was able to import [the parser library](https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-video-streams-parser-library/1.2.5) into [this android project](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android) by adding this to build.gradle:
```
implementation('com.amazonaws:amazon-kinesis-video-streams-parser-library:1.2.5') {
    transitive = false
}
```

<img width="589" alt="image" src="https://github.com/aws/amazon-kinesis-video-streams-parser-library/assets/14988194/6e286a01-f829-47e3-bfb8-f192cf574bdd">

Note that in the other project, we have the android versions of the aws-sdk-java already imported from the [other dependencies](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/master/app/build.gradle#L36), which is why we needed to use `transitive = false` to exclude those modules to avoid duplicates:
```
Duplicate class com.amazonaws.AbortedException found in modules aws-android-sdk-core-2.73.0-runtime (com.amazonaws:aws-android-sdk-core:2.73.0) and aws-java-sdk-core-1.12.406 (com.amazonaws:aws-java-sdk-core:1.12.406)
Duplicate class com.amazonaws.AmazonClientException found in modules aws-android-sdk-core-2.73.0-runtime (com.amazonaws:aws-android-sdk-core:2.73.0) and aws-java-sdk-core-1.12.406 (com.amazonaws:aws-java-sdk-core:1.12.406)
Duplicate class com.amazonaws.AmazonServiceException found in modules aws-android-sdk-core-2.73.0-runtime (com.amazonaws:aws-android-sdk-core:2.73.0) and aws-java-sdk-core-1.12.406 (com.amazonaws:aws-java-sdk-core:1.12.406)
Duplicate class com.amazonaws.AmazonServiceException$ErrorType found in modules aws-android-sdk-core-2.73.0-runtime (com.amazonaws:aws-android-sdk-core:2.73.0) and aws-java-sdk-core-1.12.406 (com.amazonaws:aws-java-sdk-core:1.12.406)
...
```

Refer to the [gradle documentation](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) as well if you want to include certain transitive dependencies, but exclude some.
