### ISSUE TITLE
Extracting metadata latency

### ISSUE THREAD

**Issue by blechatellier** [aws/amazon-kinesis-video-streams-parser-library#17]
_Copy from https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/55_

Is there a more efficient way of extracting data from the stream. Attempting to pull JSON out of MKV fragments has yielded the following results:

Profiling for 10 fragments/10 frames (times in ms)
- getting fragment list took 2469 (aus to us-east-1)
- getting media (fragments) took 1927 (aus to us-east-1)
- extracting metadata took: 746 

simply running this loop 
```
while (mkvStreamReader.mightHaveNext) {
          val mkvElement: Optional[MkvElement] = mkvStreamReader.nextIfAvailable
}
```

took the following: 
594 iterations
507 ms

For extracting the data, we've used the visitor pattern, as per the SDK. The issue appears to be that even for a small number of fragments, there is a large number of elements visited (some 50x number of fragments or more).
- Is visiting each MKV element to determine if it contains the required data necessary? 
- Is there a more efficient way of extracting this data? 
- Is this just a limitation of storing data in MKV containers?
- Is the visitor pattern appropriate for this use case?

**Comment by zhiyua-git** [comment]
@pastawoua As a clarification, the parser will parse every element and if you use visitor pattern, it will visit every element. During [performance test](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/utilities/OutputSegmentMergerTest.java#L308) we ran by adding count in the loop for MKV elements, we found that long-running test could process an element in 5~10 microseconds. However, short running test take longer process time per element because JVM is not warm up. 

If you are doing a performance test, I would recommend running long-running test. 

You can still use the visitor pattern to extract the JSON. We would like to hear more details from you.

**Comment by seanajar** [comment]
@zhiyua-git Thanks for the responses. To answer your questions -

- Tests were run on an ubuntu 16 T2 mirco, c4 large showed minimal improvement

- The visitor is attempting to extract JSON from only SimpleBlocks

-  input was provided by a getMedia request.

Further testing showed that reading the input stream did show an improvement in line with your aforementioned performance test

**Comment by pastawoua** [comment]
@zhiyua-git any update on this please?

@MushMal from our discussions on the phone you recommended using a Kinesis video stream to store metadata, if latency is too slow we might have to revert to the idea of using a Kinesis data stream instead. Are we missing something here?

**Comment by MushMal** [comment]
@pastawoua just to respond to the metadata KVS vs Kinesis Data Streams. You can try using either - Kinesis Data Streams has been designed with having discrete data streaming in mind which might work better depending on your scenario. KVS is optimized more for the Video type of ingestion - however, it doesn't preclude streaming/indexing/archival of non-video types of time-encoded data.

**Comment by pastawoua** [comment]
@MushMal yes, probably will end up using Kinesis data to get the query speed we are looking for.

**Comment by unicornss** [comment]
Closing the issue for now. Please reopen if needed.
