### ISSUE TITLE
ContiniuousGetMedia is bit slower 

### ISSUE THREAD

**Issue by rkunnath** [aws/amazon-kinesis-video-streams-parser-library#57]
Hi, I have written a subscriber using GetMedia Api and it is successfully pulling the fragments from Kinesis video stream, but it is not pulling the stream with the same rate as my gstreamer producer is pushing the stream, although i am using c5.xlarge ec2 instance which gives good bandwidth

```
StartSelector selectorToUse = fragmentNumberToStartAfter.map(fn -> new StartSelector()
						.withStartSelectorType(StartSelectorType.FRAGMENT_NUMBER).withAfterFragmentNumber(fn))
						.orElse(startSelector);
				result = this.videoMedia.getMedia(
						new GetMediaRequest().withStreamName(this.streamName).withStartSelector(selectorToUse));
```

**Comment by Tangotrax** [comment]
Hi @rkunnath : we are facing the same problem, you able to resolve this. If yes, please provide some insights.

**Comment by MushMal** [comment]
Sorry for the delay. Do you happen to have logs from the producer side whether it falls behind? Once the stream bits are in the backend, the delay is minimal (single digit ms) to get it out as GetMedia is the "real-time" path.

I would encourage to get debug logs from the producer side - I would imagine the delay might be due to the producer buffer being filled due to networking pressures. As your "consumer" is on an EC2 instance with no bandwidth concerns.
