### ISSUE TITLE
Streaming multiple web clients

### ISSUE THREAD

**Issue by tzahiba** [aws/amazon-kinesis-video-streams-parser-library#86]
Hello, I have a question regarding Kinesis video stream.

I would like to stream from my clients browser to Kinesis Video Stream, and later on use it.
I dont need the clients to interact with each other, but i am using kinesis as a recorder thus using the infrastructure it is built on.
Would this be a best practice to use Kinesis?
Thanks.

**Comment by MushMal** [comment]
@tzahiba the main difficulty is that the browser has a sandboxed media pipeline. If you find a way to get the media then you would be able to stream in. We have a range of native producer SDKs and an ASK in Java which wraps around the native to help to stream using elementary stream. However, if you are able to extract the video in a streamable MKV format, you can use PutMedia backend API directly.

Sorry, I know this is not a lot of information but the problem is that the browser is a confined environment and most browsers don't support "plugins" which would handle it.

**Comment by ranman** [comment]
What specifically are you trying to record? The browser page itself? You may be able to get a screen recording with a webrtc API and then stream the media in that way: https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-js.html
